//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuffs_And_Cufflinks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Size
    {
        public Table_Size()
        {
            this.Table_products = new HashSet<Table_products>();
        }
    
        public int s_id { get; set; }
        public string s_size { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual Table_Category Table_Category { get; set; }
        public virtual ICollection<Table_products> Table_products { get; set; }
    }
}
