//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cuff_And_Cufflinks_DBEntities : DbContext
    {
        public Cuff_And_Cufflinks_DBEntities()
            : base("name=Cuff_And_Cufflinks_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Registeration> Table_Registeration { get; set; }
        public virtual DbSet<Table_Category> Table_Category { get; set; }
        public virtual DbSet<Table_Colors> Table_Colors { get; set; }
        public virtual DbSet<Table_products> Table_products { get; set; }
        public virtual DbSet<Table_Size> Table_Size { get; set; }
    }
}
