//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Table_Category
    {
        public Table_Category()
        {
            this.Table_Colors = new HashSet<Table_Colors>();
            this.Table_products = new HashSet<Table_products>();
            this.Table_Size = new HashSet<Table_Size>();
        }
         [Required]
        public int category_id { get; set; }
         [Required]
        public string category_name { get; set; }
    
        public virtual ICollection<Table_Colors> Table_Colors { get; set; }
        public virtual ICollection<Table_products> Table_products { get; set; }
        public virtual ICollection<Table_Size> Table_Size { get; set; }
    }
}
